audit_header: false
title: Kansas City Real Estate Video Blog with Ben Bond
description: Our mission at Ben Bond Real Estate is to be your best resource for Kansas City real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Ben Bond Real Estate, your professional Kansas City Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Ben Bond
  title:
  license_number:
  about_markdown: |
    Ben Bond Real Estate will provide a 16 POINT PLAN OF ACTION, a list of numbers to help us work together towards the successful purchase and/or sale of your HOME.

    Ben Bond Real Estate will help you from start to finish. If you are looking to build, we will help you with questions when interviewing builders.

    To ensure that your closing date is met, we will assist you in the process that can seem overwhelming at times. A lot of For Sale By Owners (FSBO), come to us because they don't have a marketing plan or know the next step. Let us help you and protect you when buying or selling your home. It is one of the largest purchases you will ever make.
  brand: Ben Bond Real Estate
  brokerage: Keller Williams
  market: Kansas City
  address: 310 NW Englewood Rd, Kansas City, MO 64118
  phone: 816-268-4424
  phone_type: Office
  phone2: 816-810-5990
  phone2_type: Mobile
  email: benbond@kw.com
  url: https://www.benbondrealestate.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.freehomevaluesreports.com/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.benbondrealestate.com/listings-search/#/-366121697

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Kansas City Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.freehomevaluesreports.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Kansas City Home?"
    CTA_text2: "Search the entire MLS for your Kansas City home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.benbondrealestate.com/listings-search/#/-366121697

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/BenBondRealEstate
  linkedin_url: https://www.linkedin.com/in/benbond/
  youtube_url: https://www.youtube.com/channel/UCO4WWhx5YbdBTNxXY4-LEMQ
  twitter_url: https://twitter.com/BRBOND
  instagram_url: https://www.instagram.com/benbondrealestate/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Kansas City Real Estate Podcast with Ben Bond'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Kansas City Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Ben Bond Real Estate - your professional Kansas City Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Kansas City, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Ben Bond'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Kansas City Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#202f6a'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
